version: '3.7'

services:
  web: # this would become the DNS name of the container in dice.net network
    image: farrukhw/dice:ang_jsp
    init: true
    restart: always
    networks:
    - dice.net

    depends_on:  
    - mysql_db

    ports:
    - 9000-9004:8080

  mysql_db: # this would become the DNS name of the container in dice.net network
    image: farrukhw/dice:mysql_db
    init: true
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks: 
    - dice.net
 
networks:
  dice.net: